changed the nicfi landing page picture
openforis/sepal-doc pull request #310
Opened 2023-03-17 13:10 UTC by teopista

2023-03-29 21:00 UTC, 12rambau commented
hi teopista is this PR ready for review (it's on stale since last week)?

2023-03-30 11:12 UTC, 12rambau requested changes
Thanks for contributing to the documentation. Inputs from someone that is using the tool on daily basis is extremely valuable to us ! Tere are few changes that I would like you to make before merging: 
- the name of the image is including an useless number could you make it "signup.png" instead of "signup"
- I think you need to change the GIF or remove it entirely as it embeds many flows: 
  - it exposes you personnal phone, name, surname email. In short everything I need to hack you on the web. 
  - it is badly cut, I see the chrome popup window on the right when you validated the form.

2023-04-11 13:14 UTC, 12rambau commented on docs/source/setup/nicfi.rst
> +Sign up for NICFI Planet data access using the same email address associated with your GEE account. To sign up for access to the NICFI data program, go to `<https://www.planet.com/nicfi/>`_.
```suggestion
Sign up for NICFI Planet data access using the same email address associated with your GEE account. To sign up for access to the NICFI data program, go to `<https://www.planet.com/nicfi/>`_.
```

2023-04-11 13:14 UTC, 12rambau commented on docs/source/setup/nicfi.rst
> +Click on the **Sign up** button and fill in the form.
```suggestion
Click on the **Sign up** button and fill in the form.
```

2023-04-11 13:14 UTC, 12rambau commented on docs/source/setup/nicfi.rst
> +After submitting the form, an email will be sent with a link to activate your account.
```suggestion
After submitting the form, an email will be sent with a link to activate your account.
```

2023-04-11 13:18 UTC, 12rambau approved these changes
Nice job, thanks for your contribution!

2023-04-11 13:18 UTC, merged

2023-04-11 13:44 UTC, teopista commented
> 

You're welcome! Thank you too.